steps:
  - id: "yarn-install"
    name: 'node:18'
    args: ['yarn', 'install']

  - id: "typecheck"
    name: 'node:18'
    args: ['yarn', 'nuxi', 'typecheck']

  - id: "release"
    name: 'node:18'
    args: ['yarn', 'publish']
    secretEnv: ['TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/212866786838/secrets/npm-publish-token/versions/1
    env: 'TOKEN'